### ISSUE TITLE
videoInfoResponse.data is not object

### ISSUE THREAD

**Issue by wDRxxx** [thedvxchsquad/kodikwrapper#17]
При попытке получить ссылок на видео через 
```js
const result = await VideoLinks.getLinks({
      link: link.toString(),
      extended: isExtended
 });
```
Получается такая ошибочка: ``videoInfoResponse.data is not object``
Response от kodik-video-links
![image](https://github.com/thedvxchsquad/kodikwrapper/assets/81556924/8e887944-43e6-4301-8174-d3902a5b4a6f)

**Comment by neverlane** [comment]
кодик начал часто менять endpoint для получения ссылок, текущий - `/ftor`
в прошлой обнове я добавил поле `videoInfoUrl` для метода `getLinks`, используй его с текущим endpoint'ом
пока что я в процессе обновления `VideoLinks`, добавлю получение этого endpoint'а, оптимизирую получение ссылок (оказалось, что там обязательны только 3 параметра) и обновлю типы

```js
const result = await VideoLinks.getLinks({
      link: link,
      extended: isExtended,
      videoInfoUrl: '/ftor'
 });
```

**Comment by wDRxxx** [comment]
Спасибо, удачи
