### ISSUE TITLE
При вызове await VideoLinks.getLinks зависает

### ISSUE THREAD

**Issue by Glebweider** [thedvxchsquad/kodikwrapper#19]
Когда я вызываю 
  const links = await VideoLinks.getLinks({
    link, videoInfoEndpoint: endpoint
  }); 
  то у меня зависает код и дальше не проход больше

**Comment by neverlane** [comment]
такое происходит только с `VideoLinks.getLinks`? все нормально с `VideoLinks.parseLink({ link, extended: true })` и `Client` методами?

**Comment by Glebweider** [comment]
с ними тоже зависает

**Comment by neverlane** [comment]
скорее всего провайдер блокает kodik (ip, домены), попробуй под впном вызвать их

**Comment by Glebweider** [comment]
хорошо попробую позже, заранее спасибо за помощ

**Comment by Glebweider** [comment]
заработало спасибо <3
